const serv = require('./common')

describe('Master Data APIs',() => {
    let totalCases = 0;
    beforeEach(() => {
        totalCases++;
    })
    describe('Get master data',() => {
        describe('Should fetch master data by type',() => {
            it('Get Case Activity Type', async() => serv.getMasterDataByType('CASE_ACTIVITY_TYPE'))
            it('Get Case Complexity', async() => serv.getMasterDataByType('CASE_COMPLEXITY'))
            it('Get FATF Purpose', async() => serv.getMasterDataByType('CASE_FATF'))
            it('Get Case Status', async() => serv.getMasterDataByType('CASE_STATUS'))
            it('Get Foreign Country', async() => serv.getMasterDataByType('COUNTRY'))
            it('Get Department', async() => serv.getMasterDataByType('DEPARTMENT'))
            it('Get Document Type', async() => serv.getMasterDataByType('DOCUMENT_TYPE'))
            it('Get External Agency Name', async() => serv.getMasterDataByType('EXTERNAL_AGENCY_NAME'))
            it('Get External Agency Type', async() => serv.getMasterDataByType('EXTERNAL_AGENCY_TYPE'))
            it('Get File Division', async() => serv.getMasterDataByType('FILE_DIVISION'))
            it('Get File Header 1', async() => serv.getMasterDataByType('FILE_HEADER1'))
            it('Get File Header 2', async() => serv.getMasterDataByType('FILE_HEADER2'))
            it('Get File Origin', async() => serv.getMasterDataByType('FILE_ORIGIN'))
            it('Get File Year', async() => serv.getMasterDataByType('FILE_YEAR'))
            it('Get Foreign Agency Name', async() => serv.getMasterDataByType('AGENCY_NAME_FOREIGN'))
            it('Get Foreign Agency Type', async() => serv.getMasterDataByType('AGENCY_TYPE_FOREIGN'))
            it('Get MLA Case Sub Type', async() => serv.getMasterDataByType('MLA_CASE_SUB_TYPE'))
            it('Get MLA Case Type', async() => serv.getMasterDataByType('MLA_CASE_TYPE'))
            it('Get Request Complexity', async() => serv.getMasterDataByType('REQUEST_COMPLEXITY'))
            it('Get Request Mode', async() => serv.getMasterDataByType('REQUEST_MODE'))
            it('Get Request Status', async() => serv.getMasterDataByType('REQUEST_STATUS'))
            it('Get Request Type', async() => serv.getMasterDataByType('REQUEST_TYPE'))
            it('Get Request Urgency', async() => serv.getMasterDataByType('REQUEST_URGENCY'))
            it('Get Requested Under', async() => serv.getMasterDataByType('REQUESTED_UNDER'))
            it('Get Root Item', async() => serv.getMasterDataByType('ROOT_CODE'))
            it('Get Security Classification', async() => serv.getMasterDataByType('SECURITY_CLASSIFICATION'))
        })
        describe('Fetch master data by type and parent', () => {
            it('Get document type for file division 1', async() => serv.getMasterDataByTypeAndParent('DOCUMENT_TYPE','FILE_DIVISION_1'))
            it('Get document type for file division 2', async() => serv.getMasterDataByTypeAndParent('DOCUMENT_TYPE','FILE_DIVISION_2'))
            it('Get document type for file division 3', async() => serv.getMasterDataByTypeAndParent('DOCUMENT_TYPE','FILE_DIVISION_3'))
            it('Get document type for file division 4', async() => serv.getMasterDataByTypeAndParent('DOCUMENT_TYPE','FILE_DIVISION_4'))
            it('Get document type for file division 5', async() => serv.getMasterDataByTypeAndParent('DOCUMENT_TYPE','FILE_DIVISION_5'))
            it('Get external agency name for external agency type 1', async() => serv.getMasterDataByTypeAndParent('EXTERNAL_AGENCY_NAME','EXTERNAL_AGENCY_TYPE_1'))
            it('Get external agency name for external agency type 2', async() => serv.getMasterDataByTypeAndParent('EXTERNAL_AGENCY_NAME','EXTERNAL_AGENCY_TYPE_2'))
            it('Get external agency name for external agency type 3', async() => serv.getMasterDataByTypeAndParent('EXTERNAL_AGENCY_NAME','EXTERNAL_AGENCY_TYPE_3'))
            it('Get external agency name for external agency type 4', async() => serv.getMasterDataByTypeAndParent('EXTERNAL_AGENCY_NAME','EXTERNAL_AGENCY_TYPE_4'))
            it('Get external agency name for external agency type 5', async() => serv.getMasterDataByTypeAndParent('EXTERNAL_AGENCY_NAME','EXTERNAL_AGENCY_TYPE_5'))
            it('Get file division for root item', async() => serv.getMasterDataByTypeAndParent('FILE_DIVISION','ROOT_CODE_1'))
            it('Get file header 1 for circulation officer', async() => serv.getMasterDataByTypeAndParent('FILE_HEADER1','CIRCULATION OFFICER'))
            it('Get file header 1 for file division 4', async() => serv.getMasterDataByTypeAndParent('FILE_HEADER1','FILE_DIVISION_4'))
            it('Get file header 1 for file division 5', async() => serv.getMasterDataByTypeAndParent('FILE_HEADER1','FILE_DIVISION_5'))
            it('Get file header 1 for legal officer', async() => serv.getMasterDataByTypeAndParent('FILE_HEADER1','LEGAL OFFICER'))
            it('Get file header 1 for registry (IAD)', async() => serv.getMasterDataByTypeAndParent('FILE_HEADER1','REGISTRY (IAD)'))
            it('Get file header 2 for file header 1 ADVISORY', async() => serv.getMasterDataByTypeAndParent('FILE_HEADER2','ADVISORY'))
            it('Get file header 2 for file header 1 EXTRADITION', async() => serv.getMasterDataByTypeAndParent('FILE_HEADER2','EXTRADITION'))
            it('Get file header 2 for file header 1 FILE_HEADER1_1_2', async() => serv.getMasterDataByTypeAndParent('FILE_HEADER2','FILE_HEADER1_1_2'))
            it('Get file header 2 for file header 1 FILE_HEADER1_1_3', async() => serv.getMasterDataByTypeAndParent('FILE_HEADER2','FILE_HEADER1_1_3'))
            it('Get file header 2 for file header 1 FILE_HEADER1_1_4', async() => serv.getMasterDataByTypeAndParent('FILE_HEADER2','FILE_HEADER1_1_4'))
            it('Get file header 2 for file header 1 FILE_HEADER1_2_3', async() => serv.getMasterDataByTypeAndParent('FILE_HEADER2','FILE_HEADER1_2_3'))
            it('Get file header 2 for file header 1 FILE_HEADER1_2_4', async() => serv.getMasterDataByTypeAndParent('FILE_HEADER2','FILE_HEADER1_2_4'))
            it('Get file header 2 for file header 1 FILE_HEADER1_2_5', async() => serv.getMasterDataByTypeAndParent('FILE_HEADER2','FILE_HEADER1_2_5'))
            it('Get file header 2 for file header 1 FILE_HEADER1_3_2', async() => serv.getMasterDataByTypeAndParent('FILE_HEADER2','FILE_HEADER1_3_2'))
            it('Get file header 2 for file header 1 FILE_HEADER1_3_3', async() => serv.getMasterDataByTypeAndParent('FILE_HEADER2','FILE_HEADER1_3_3'))
            it('Get file header 2 for file header 1 FILE_HEADER1_3_4', async() => serv.getMasterDataByTypeAndParent('FILE_HEADER2','FILE_HEADER1_3_4'))
            it('Get file header 2 for file header 1 FILE_HEADER1_3_5', async() => serv.getMasterDataByTypeAndParent('FILE_HEADER2','FILE_HEADER1_3_5'))
            it('Get file header 2 for file header 1 FILE_HEADER1_4_1', async() => serv.getMasterDataByTypeAndParent('FILE_HEADER2','FILE_HEADER1_4_1'))
            it('Get file header 2 for file header 1 FILE_HEADER1_4_2', async() => serv.getMasterDataByTypeAndParent('FILE_HEADER2','FILE_HEADER1_4_2'))
            it('Get file header 2 for file header 1 FILE_HEADER1_4_3', async() => serv.getMasterDataByTypeAndParent('FILE_HEADER2','FILE_HEADER1_4_3'))
            it('Get file header 2 for file header 1 FILE_HEADER1_4_4', async() => serv.getMasterDataByTypeAndParent('FILE_HEADER2','FILE_HEADER1_4_4'))
            it('Get file header 2 for file header 1 FILE_HEADER1_4_5', async() => serv.getMasterDataByTypeAndParent('FILE_HEADER2','FILE_HEADER1_4_5'))
            it('Get file header 2 for file header 1 FILE_HEADER1_5_1', async() => serv.getMasterDataByTypeAndParent('FILE_HEADER2','FILE_HEADER1_5_1'))
            it('Get file header 2 for file header 1 FILE_HEADER1_5_2', async() => serv.getMasterDataByTypeAndParent('FILE_HEADER2','FILE_HEADER1_5_2'))
            it('Get file header 2 for file header 1 FILE_HEADER1_5_3', async() => serv.getMasterDataByTypeAndParent('FILE_HEADER2','FILE_HEADER1_5_3'))
            it('Get file header 2 for file header 1 FILE_HEADER1_5_4', async() => serv.getMasterDataByTypeAndParent('FILE_HEADER2','FILE_HEADER1_5_4'))
            it('Get file header 2 for file header 1 FILE_HEADER1_5_5', async() => serv.getMasterDataByTypeAndParent('FILE_HEADER2','FILE_HEADER1_5_5'))
            it('Get file header 2 for file header 1 MLA', async() => serv.getMasterDataByTypeAndParent('FILE_HEADER2','MLA'))
            it('Get foreign agency name for foreign agency type 1', async() => serv.getMasterDataByTypeAndParent('AGENCY_NAME_FOREIGN','AGENCY_TYPE_FOREIGN_1'))
            it('Get foreign agency name for foreign agency type 2', async() => serv.getMasterDataByTypeAndParent('AGENCY_NAME_FOREIGN','AGENCY_TYPE_FOREIGN_2'))
            it('Get foreign agency name for foreign agency type 3', async() => serv.getMasterDataByTypeAndParent('AGENCY_NAME_FOREIGN','AGENCY_TYPE_FOREIGN_3'))
            it('Get foreign agency name for foreign agency type 4', async() => serv.getMasterDataByTypeAndParent('AGENCY_NAME_FOREIGN','AGENCY_TYPE_FOREIGN_4'))
            it('Get foreign agency name for foreign agency type 5', async() => serv.getMasterDataByTypeAndParent('AGENCY_NAME_FOREIGN','AGENCY_TYPE_FOREIGN_5'))
            it('Get foreign agency type for foreign country 1', async() => serv.getMasterDataByTypeAndParent('AGENCY_TYPE_FOREIGN','COUNTRY_1'))
            it('Get foreign agency type for foreign country 2', async() => serv.getMasterDataByTypeAndParent('AGENCY_TYPE_FOREIGN','COUNTRY_2'))
            it('Get foreign agency type for foreign country 3', async() => serv.getMasterDataByTypeAndParent('AGENCY_TYPE_FOREIGN','COUNTRY_3'))
            it('Get foreign agency type for foreign country 4', async() => serv.getMasterDataByTypeAndParent('AGENCY_TYPE_FOREIGN','COUNTRY_4'))
            it('Get foreign agency type for foreign country 5', async() => serv.getMasterDataByTypeAndParent('AGENCY_TYPE_FOREIGN','COUNTRY_5'))
            it('Get MLA case sub type for MLA case type 1', async() => serv.getMasterDataByTypeAndParent('MLA_CASE_SUB_TYPE','MLA_CASE_TYPE_1'))
            it('Get MLA case sub type for MLA case type 2', async() => serv.getMasterDataByTypeAndParent('MLA_CASE_SUB_TYPE','MLA_CASE_TYPE_2'))
            it('Get MLA case sub type for MLA case type 3', async() => serv.getMasterDataByTypeAndParent('MLA_CASE_SUB_TYPE','MLA_CASE_TYPE_3'))
            it('Get MLA case sub type for MLA case type 4', async() => serv.getMasterDataByTypeAndParent('MLA_CASE_SUB_TYPE','MLA_CASE_TYPE_4'))
            it('Get MLA case sub type for MLA case type 5', async() => serv.getMasterDataByTypeAndParent('MLA_CASE_SUB_TYPE','MLA_CASE_TYPE_5'))
            it('Get requested under for extradition', async() => serv.getMasterDataByTypeAndParent('REQUEST_UNDER_EXTRADITION','COUNTRY_1'))
            it('Get requested under for MLA', async() => serv.getMasterDataByTypeAndParent('REQUEST_UNDER_MLA','COUNTRY_2'))
        })
        describe('Fetch master data by code', () => {
            it('Get 2019', async() => serv.getMasterDataByCode('2019'))
            it('Get 2020', async() => serv.getMasterDataByCode('2020'))
            it('Get 2021', async() => serv.getMasterDataByCode('2021'))
            it('Get 2022', async() => serv.getMasterDataByCode('2022'))
            it('Get 2023', async() => serv.getMasterDataByCode('2023'))
            it('Get ADDR_F', async() => serv.getMasterDataByCode('ADDR_F'))
            it('Get ADDR_L', async() => serv.getMasterDataByCode('ADDR_L'))
            it('Get ADVISORY', async() => serv.getMasterDataByCode('ADVISORY'))
            it('Get AGENCY_NAME_FOREIGN_1_1', async() => serv.getMasterDataByCode('AGENCY_NAME_FOREIGN_1_1'))
            it('Get AGENCY_NAME_FOREIGN_1_2', async() => serv.getMasterDataByCode('AGENCY_NAME_FOREIGN_1_2'))
            it('Get AGENCY_NAME_FOREIGN_1_3', async() => serv.getMasterDataByCode('AGENCY_NAME_FOREIGN_1_3'))
            it('Get AGENCY_NAME_FOREIGN_1_4', async() => serv.getMasterDataByCode('AGENCY_NAME_FOREIGN_1_4'))
            it('Get AGENCY_NAME_FOREIGN_1_5', async() => serv.getMasterDataByCode('AGENCY_NAME_FOREIGN_1_5'))
            it('Get AGENCY_NAME_FOREIGN_2_1', async() => serv.getMasterDataByCode('AGENCY_NAME_FOREIGN_2_1'))
            it('Get AGENCY_NAME_FOREIGN_2_2', async() => serv.getMasterDataByCode('AGENCY_NAME_FOREIGN_2_2'))
            it('Get AGENCY_NAME_FOREIGN_2_3', async() => serv.getMasterDataByCode('AGENCY_NAME_FOREIGN_2_3'))
            it('Get AGENCY_NAME_FOREIGN_2_4', async() => serv.getMasterDataByCode('AGENCY_NAME_FOREIGN_2_4'))
            it('Get AGENCY_NAME_FOREIGN_2_5', async() => serv.getMasterDataByCode('AGENCY_NAME_FOREIGN_2_5'))
            it('Get AGENCY_NAME_FOREIGN_3_1', async() => serv.getMasterDataByCode('AGENCY_NAME_FOREIGN_3_1'))
            it('Get AGENCY_NAME_FOREIGN_3_2', async() => serv.getMasterDataByCode('AGENCY_NAME_FOREIGN_3_2'))
            it('Get AGENCY_NAME_FOREIGN_3_3', async() => serv.getMasterDataByCode('AGENCY_NAME_FOREIGN_3_3'))
            it('Get AGENCY_NAME_FOREIGN_3_4', async() => serv.getMasterDataByCode('AGENCY_NAME_FOREIGN_3_4'))
            it('Get AGENCY_NAME_FOREIGN_3_5', async() => serv.getMasterDataByCode('AGENCY_NAME_FOREIGN_3_5'))
            it('Get AGENCY_NAME_FOREIGN_4_1', async() => serv.getMasterDataByCode('AGENCY_NAME_FOREIGN_4_1'))
            it('Get AGENCY_NAME_FOREIGN_4_2', async() => serv.getMasterDataByCode('AGENCY_NAME_FOREIGN_4_2'))
            it('Get AGENCY_NAME_FOREIGN_4_3', async() => serv.getMasterDataByCode('AGENCY_NAME_FOREIGN_4_3'))
            it('Get AGENCY_NAME_FOREIGN_4_4', async() => serv.getMasterDataByCode('AGENCY_NAME_FOREIGN_4_4'))
            it('Get AGENCY_NAME_FOREIGN_4_5', async() => serv.getMasterDataByCode('AGENCY_NAME_FOREIGN_4_5'))
            it('Get AGENCY_NAME_FOREIGN_5_1', async() => serv.getMasterDataByCode('AGENCY_NAME_FOREIGN_5_1'))
            it('Get AGENCY_NAME_FOREIGN_5_2', async() => serv.getMasterDataByCode('AGENCY_NAME_FOREIGN_5_2'))
            it('Get AGENCY_NAME_FOREIGN_5_3', async() => serv.getMasterDataByCode('AGENCY_NAME_FOREIGN_5_3'))
            it('Get AGENCY_NAME_FOREIGN_5_4', async() => serv.getMasterDataByCode('AGENCY_NAME_FOREIGN_5_4'))
            it('Get AGENCY_NAME_FOREIGN_5_5', async() => serv.getMasterDataByCode('AGENCY_NAME_FOREIGN_5_5'))
            it('Get AGENCY_TYPE_FOREIGN_1', async() => serv.getMasterDataByCode('AGENCY_TYPE_FOREIGN_1'))
            it('Get AGENCY_TYPE_FOREIGN_2', async() => serv.getMasterDataByCode('AGENCY_TYPE_FOREIGN_2'))
            it('Get AGENCY_TYPE_FOREIGN_3', async() => serv.getMasterDataByCode('AGENCY_TYPE_FOREIGN_3'))
            it('Get AGENCY_TYPE_FOREIGN_4', async() => serv.getMasterDataByCode('AGENCY_TYPE_FOREIGN_4'))
            it('Get AGENCY_TYPE_FOREIGN_5', async() => serv.getMasterDataByCode('AGENCY_TYPE_FOREIGN_5'))
            it('Get CASE_ACTIVITY_TYPE_1', async() => serv.getMasterDataByCode('CASE_ACTIVITY_TYPE_1'))
            it('Get CASE_ACTIVITY_TYPE_2', async() => serv.getMasterDataByCode('CASE_ACTIVITY_TYPE_2'))
            it('Get CASE_ACTIVITY_TYPE_3', async() => serv.getMasterDataByCode('CASE_ACTIVITY_TYPE_3'))
            it('Get CASE_ACTIVITY_TYPE_4', async() => serv.getMasterDataByCode('CASE_ACTIVITY_TYPE_4'))
            it('Get CASE_ACTIVITY_TYPE_5', async() => serv.getMasterDataByCode('CASE_ACTIVITY_TYPE_5'))
            it('Get CASE_COMPLEXITY_1', async() => serv.getMasterDataByCode('CASE_COMPLEXITY_1'))
            it('Get CASE_COMPLEXITY_2', async() => serv.getMasterDataByCode('CASE_COMPLEXITY_2'))
            it('Get CASE_COMPLEXITY_3', async() => serv.getMasterDataByCode('CASE_COMPLEXITY_3'))
            it('Get CASE_COMPLEXITY_4', async() => serv.getMasterDataByCode('CASE_COMPLEXITY_4'))
            it('Get CASE_COMPLEXITY_5', async() => serv.getMasterDataByCode('CASE_COMPLEXITY_5'))
            it('Get CASE_FATF_1', async() => serv.getMasterDataByCode('CASE_FATF_1'))
            it('Get CASE_FATF_2', async() => serv.getMasterDataByCode('CASE_FATF_2'))
            it('Get CASE_FATF_3', async() => serv.getMasterDataByCode('CASE_FATF_3'))
            it('Get CASE_FATF_4', async() => serv.getMasterDataByCode('CASE_FATF_4'))
            it('Get CASE_FATF_5', async() => serv.getMasterDataByCode('CASE_FATF_5'))
            it('Get CASE_STATUS_1', async() => serv.getMasterDataByCode('CASE_STATUS_1'))
            it('Get CASE_STATUS_2', async() => serv.getMasterDataByCode('CASE_STATUS_2'))
            it('Get CASE_STATUS_3', async() => serv.getMasterDataByCode('CASE_STATUS_3'))
            it('Get CIRCULATION OFFICER', async() => serv.getMasterDataByCode('CIRCULATION OFFICER'))
            it('Get COUNTRY_1', async() => serv.getMasterDataByCode('COUNTRY_1'))
            it('Get COUNTRY_2', async() => serv.getMasterDataByCode('COUNTRY_2'))
            it('Get COUNTRY_3', async() => serv.getMasterDataByCode('COUNTRY_3'))
            it('Get COUNTRY_4', async() => serv.getMasterDataByCode('COUNTRY_4'))
            it('Get COUNTRY_5', async() => serv.getMasterDataByCode('COUNTRY_5'))
            it('Get CSTAT_DO', async() => serv.getMasterDataByCode('CSTAT_DO'))
            it('Get CSTAT_O', async() => serv.getMasterDataByCode('CSTAT_O'))
            it('Get D1', async() => serv.getMasterDataByCode('D1'))
            it('Get D2', async() => serv.getMasterDataByCode('D2'))
            it('Get D3', async() => serv.getMasterDataByCode('D3'))
            it('Get EXTERNAL_AGENCY_NAME_1_1', async() => serv.getMasterDataByCode('EXTERNAL_AGENCY_NAME_1_1'))
            it('Get EXTERNAL_AGENCY_NAME_1_2', async() => serv.getMasterDataByCode('EXTERNAL_AGENCY_NAME_1_2'))
            it('Get EXTERNAL_AGENCY_NAME_1_3', async() => serv.getMasterDataByCode('EXTERNAL_AGENCY_NAME_1_3'))
            it('Get EXTERNAL_AGENCY_NAME_1_4', async() => serv.getMasterDataByCode('EXTERNAL_AGENCY_NAME_1_4'))
            it('Get EXTERNAL_AGENCY_NAME_1_5', async() => serv.getMasterDataByCode('EXTERNAL_AGENCY_NAME_1_5'))
            it('Get EXTERNAL_AGENCY_NAME_2_1', async() => serv.getMasterDataByCode('EXTERNAL_AGENCY_NAME_2_1'))
            it('Get EXTERNAL_AGENCY_NAME_2_2', async() => serv.getMasterDataByCode('EXTERNAL_AGENCY_NAME_2_2'))
            it('Get EXTERNAL_AGENCY_NAME_2_3', async() => serv.getMasterDataByCode('EXTERNAL_AGENCY_NAME_2_3'))
            it('Get EXTERNAL_AGENCY_NAME_2_4', async() => serv.getMasterDataByCode('EXTERNAL_AGENCY_NAME_2_4'))
            it('Get EXTERNAL_AGENCY_NAME_2_5', async() => serv.getMasterDataByCode('EXTERNAL_AGENCY_NAME_2_5'))
            it('Get EXTERNAL_AGENCY_NAME_3_1', async() => serv.getMasterDataByCode('EXTERNAL_AGENCY_NAME_3_1'))
            it('Get EXTERNAL_AGENCY_NAME_3_2', async() => serv.getMasterDataByCode('EXTERNAL_AGENCY_NAME_3_2'))
            it('Get EXTERNAL_AGENCY_NAME_3_3', async() => serv.getMasterDataByCode('EXTERNAL_AGENCY_NAME_3_3'))
            it('Get EXTERNAL_AGENCY_NAME_3_4', async() => serv.getMasterDataByCode('EXTERNAL_AGENCY_NAME_3_4'))
            it('Get EXTERNAL_AGENCY_NAME_3_5', async() => serv.getMasterDataByCode('EXTERNAL_AGENCY_NAME_3_5'))
            it('Get EXTERNAL_AGENCY_NAME_4_1', async() => serv.getMasterDataByCode('EXTERNAL_AGENCY_NAME_4_1'))
            it('Get EXTERNAL_AGENCY_NAME_4_2', async() => serv.getMasterDataByCode('EXTERNAL_AGENCY_NAME_4_2'))
            it('Get EXTERNAL_AGENCY_NAME_4_3', async() => serv.getMasterDataByCode('EXTERNAL_AGENCY_NAME_4_3'))
            it('Get EXTERNAL_AGENCY_NAME_4_4', async() => serv.getMasterDataByCode('EXTERNAL_AGENCY_NAME_4_4'))
            it('Get EXTERNAL_AGENCY_NAME_4_5', async() => serv.getMasterDataByCode('EXTERNAL_AGENCY_NAME_4_5'))
            it('Get EXTERNAL_AGENCY_NAME_5_1', async() => serv.getMasterDataByCode('EXTERNAL_AGENCY_NAME_5_1'))
            it('Get EXTERNAL_AGENCY_NAME_5_2', async() => serv.getMasterDataByCode('EXTERNAL_AGENCY_NAME_5_2'))
            it('Get EXTERNAL_AGENCY_NAME_5_3', async() => serv.getMasterDataByCode('EXTERNAL_AGENCY_NAME_5_3'))
            it('Get EXTERNAL_AGENCY_NAME_5_4', async() => serv.getMasterDataByCode('EXTERNAL_AGENCY_NAME_5_4'))
            it('Get EXTERNAL_AGENCY_NAME_5_5', async() => serv.getMasterDataByCode('EXTERNAL_AGENCY_NAME_5_5'))
            it('Get EXTERNAL_AGENCY_TYPE_1', async() => serv.getMasterDataByCode('EXTERNAL_AGENCY_TYPE_1'))
            it('Get EXTERNAL_AGENCY_TYPE_2', async() => serv.getMasterDataByCode('EXTERNAL_AGENCY_TYPE_2'))
            it('Get EXTERNAL_AGENCY_TYPE_3', async() => serv.getMasterDataByCode('EXTERNAL_AGENCY_TYPE_3'))
            it('Get EXTERNAL_AGENCY_TYPE_4', async() => serv.getMasterDataByCode('EXTERNAL_AGENCY_TYPE_4'))
            it('Get EXTERNAL_AGENCY_TYPE_5', async() => serv.getMasterDataByCode('EXTERNAL_AGENCY_TYPE_5'))
            it('Get EXTR-F', async() => serv.getMasterDataByCode('EXTR-F'))
            it('Get EXTR-T', async() => serv.getMasterDataByCode('EXTR-T'))
            it('Get EXTRADITION', async() => serv.getMasterDataByCode('EXTRADITION'))
            it('Get EXTRADITION_CASE', async() => serv.getMasterDataByCode('EXTRADITION_CASE'))
            it('Get FILE_DIVISION_1_DOC_1', async() => serv.getMasterDataByCode('FILE_DIVISION_1_DOC_1'))
            it('Get FILE_DIVISION_1_DOC_2', async() => serv.getMasterDataByCode('FILE_DIVISION_1_DOC_2'))
            it('Get FILE_DIVISION_1_DOC_3', async() => serv.getMasterDataByCode('FILE_DIVISION_1_DOC_3'))
            it('Get FILE_DIVISION_1_DOC_4', async() => serv.getMasterDataByCode('FILE_DIVISION_1_DOC_4'))
            it('Get FILE_DIVISION_1_DOC_5', async() => serv.getMasterDataByCode('FILE_DIVISION_1_DOC_5'))
            it('Get FILE_DIVISION_2_DOC_1', async() => serv.getMasterDataByCode('FILE_DIVISION_2_DOC_1'))
            it('Get FILE_DIVISION_2_DOC_2', async() => serv.getMasterDataByCode('FILE_DIVISION_2_DOC_2'))
            it('Get FILE_DIVISION_2_DOC_3', async() => serv.getMasterDataByCode('FILE_DIVISION_2_DOC_3'))
            it('Get FILE_DIVISION_2_DOC_4', async() => serv.getMasterDataByCode('FILE_DIVISION_2_DOC_4'))
            it('Get FILE_DIVISION_2_DOC_5', async() => serv.getMasterDataByCode('FILE_DIVISION_2_DOC_5'))
            it('Get FILE_DIVISION_3_DOC_1', async() => serv.getMasterDataByCode('FILE_DIVISION_3_DOC_1'))
            it('Get FILE_DIVISION_3_DOC_2', async() => serv.getMasterDataByCode('FILE_DIVISION_3_DOC_2'))
            it('Get FILE_DIVISION_3_DOC_3', async() => serv.getMasterDataByCode('FILE_DIVISION_3_DOC_3'))
            it('Get FILE_DIVISION_3_DOC_4', async() => serv.getMasterDataByCode('FILE_DIVISION_3_DOC_4'))
            it('Get FILE_DIVISION_3_DOC_5', async() => serv.getMasterDataByCode('FILE_DIVISION_3_DOC_5'))
            it('Get FILE_DIVISION_4', async() => serv.getMasterDataByCode('FILE_DIVISION_4'))
            it('Get FILE_DIVISION_4_DOC_1', async() => serv.getMasterDataByCode('FILE_DIVISION_4_DOC_1'))
            it('Get FILE_DIVISION_4_DOC_2', async() => serv.getMasterDataByCode('FILE_DIVISION_4_DOC_2'))
            it('Get FILE_DIVISION_4_DOC_3', async() => serv.getMasterDataByCode('FILE_DIVISION_4_DOC_3'))
            it('Get FILE_DIVISION_4_DOC_4', async() => serv.getMasterDataByCode('FILE_DIVISION_4_DOC_4'))
            it('Get FILE_DIVISION_4_DOC_5', async() => serv.getMasterDataByCode('FILE_DIVISION_4_DOC_5'))
            it('Get FILE_DIVISION_5', async() => serv.getMasterDataByCode('FILE_DIVISION_5'))
            it('Get FILE_DIVISION_5_DOC_1', async() => serv.getMasterDataByCode('FILE_DIVISION_5_DOC_1'))
            it('Get FILE_DIVISION_5_DOC_2', async() => serv.getMasterDataByCode('FILE_DIVISION_5_DOC_2'))
            it('Get FILE_DIVISION_5_DOC_3', async() => serv.getMasterDataByCode('FILE_DIVISION_5_DOC_3'))
            it('Get FILE_DIVISION_5_DOC_4', async() => serv.getMasterDataByCode('FILE_DIVISION_5_DOC_4'))
            it('Get FILE_DIVISION_5_DOC_5', async() => serv.getMasterDataByCode('FILE_DIVISION_5_DOC_5'))
            it('Get FILE_HEADER1_1_2', async() => serv.getMasterDataByCode('FILE_HEADER1_1_2'))
            it('Get FILE_HEADER1_1_3', async() => serv.getMasterDataByCode('FILE_HEADER1_1_3'))
            it('Get FILE_HEADER1_1_4', async() => serv.getMasterDataByCode('FILE_HEADER1_1_4'))
            it('Get FILE_HEADER1_1_5', async() => serv.getMasterDataByCode('FILE_HEADER1_1_5'))
            it('Get FILE_HEADER1_2_2', async() => serv.getMasterDataByCode('FILE_HEADER1_2_2'))
            it('Get FILE_HEADER1_2_3', async() => serv.getMasterDataByCode('FILE_HEADER1_2_3'))
            it('Get FILE_HEADER1_2_4', async() => serv.getMasterDataByCode('FILE_HEADER1_2_4'))
            it('Get FILE_HEADER1_2_5', async() => serv.getMasterDataByCode('FILE_HEADER1_2_5'))
            it('Get FILE_HEADER1_3_2', async() => serv.getMasterDataByCode('FILE_HEADER1_3_2'))
            it('Get FILE_HEADER1_3_3', async() => serv.getMasterDataByCode('FILE_HEADER1_3_3'))
            it('Get FILE_HEADER1_3_4', async() => serv.getMasterDataByCode('FILE_HEADER1_3_4'))
            it('Get FILE_HEADER1_3_5', async() => serv.getMasterDataByCode('FILE_HEADER1_3_5'))
            it('Get FILE_HEADER1_4_1', async() => serv.getMasterDataByCode('FILE_HEADER1_4_1'))
            it('Get FILE_HEADER1_4_2', async() => serv.getMasterDataByCode('FILE_HEADER1_4_2'))
            it('Get FILE_HEADER1_4_3', async() => serv.getMasterDataByCode('FILE_HEADER1_4_3'))
            it('Get FILE_HEADER1_4_4', async() => serv.getMasterDataByCode('FILE_HEADER1_4_4'))
            it('Get FILE_HEADER1_4_5', async() => serv.getMasterDataByCode('FILE_HEADER1_4_5'))
            it('Get FILE_HEADER1_5_1', async() => serv.getMasterDataByCode('FILE_HEADER1_5_1'))
            it('Get FILE_HEADER1_5_2', async() => serv.getMasterDataByCode('FILE_HEADER1_5_2'))
            it('Get FILE_HEADER1_5_3', async() => serv.getMasterDataByCode('FILE_HEADER1_5_3'))
            it('Get FILE_HEADER1_5_4', async() => serv.getMasterDataByCode('FILE_HEADER1_5_4'))
            it('Get FILE_HEADER1_5_5', async() => serv.getMasterDataByCode('FILE_HEADER1_5_5'))
            it('Get FILE_HEADER2_1_2', async() => serv.getMasterDataByCode('FILE_HEADER2_1_2'))
            it('Get FILE_HEADER2_1_3', async() => serv.getMasterDataByCode('FILE_HEADER2_1_3'))
            it('Get FILE_HEADER2_1_4', async() => serv.getMasterDataByCode('FILE_HEADER2_1_4'))
            it('Get FILE_HEADER2_2_3', async() => serv.getMasterDataByCode('FILE_HEADER2_2_3'))
            it('Get FILE_HEADER2_2_4', async() => serv.getMasterDataByCode('FILE_HEADER2_2_4'))
            it('Get FILE_HEADER2_2_5', async() => serv.getMasterDataByCode('FILE_HEADER2_2_5'))
            it('Get FILE_HEADER2_3_1', async() => serv.getMasterDataByCode('FILE_HEADER2_3_1'))
            it('Get FILE_HEADER2_3_2', async() => serv.getMasterDataByCode('FILE_HEADER2_3_2'))
            it('Get FILE_HEADER2_3_3', async() => serv.getMasterDataByCode('FILE_HEADER2_3_3'))
            it('Get FILE_HEADER2_3_4', async() => serv.getMasterDataByCode('FILE_HEADER2_3_4'))
            it('Get FILE_HEADER2_3_5', async() => serv.getMasterDataByCode('FILE_HEADER2_3_5'))
            it('Get FILE_HEADER2_4_1', async() => serv.getMasterDataByCode('FILE_HEADER2_4_1'))
            it('Get FILE_HEADER2_4_2', async() => serv.getMasterDataByCode('FILE_HEADER2_4_2'))
            it('Get FILE_HEADER2_4_3', async() => serv.getMasterDataByCode('FILE_HEADER2_4_3'))
            it('Get FILE_HEADER2_4_4', async() => serv.getMasterDataByCode('FILE_HEADER2_4_4'))
            it('Get FILE_HEADER2_4_5', async() => serv.getMasterDataByCode('FILE_HEADER2_4_5'))
            it('Get FILE_HEADER2_5_1', async() => serv.getMasterDataByCode('FILE_HEADER2_5_1'))
            it('Get FILE_HEADER2_5_2', async() => serv.getMasterDataByCode('FILE_HEADER2_5_2'))
            it('Get FILE_HEADER2_5_3', async() => serv.getMasterDataByCode('FILE_HEADER2_5_3'))
            it('Get FILE_HEADER2_5_4', async() => serv.getMasterDataByCode('FILE_HEADER2_5_4'))
            it('Get FILE_HEADER2_5_5', async() => serv.getMasterDataByCode('FILE_HEADER2_5_5'))
            it('Get I', async() => serv.getMasterDataByCode('I'))
            it('Get LEGAL OFFICER', async() => serv.getMasterDataByCode('LEGAL OFFICER'))
            it('Get MLA', async() => serv.getMasterDataByCode('MLA'))
            it('Get MLA_CASE', async() => serv.getMasterDataByCode('MLA_CASE'))
            it('Get MLA_CASE_SUB_TYPE_1_3', async() => serv.getMasterDataByCode('MLA_CASE_SUB_TYPE_1_3'))
            it('Get MLA_CASE_SUB_TYPE_1_4', async() => serv.getMasterDataByCode('MLA_CASE_SUB_TYPE_1_4'))
            it('Get MLA_CASE_SUB_TYPE_1_5', async() => serv.getMasterDataByCode('MLA_CASE_SUB_TYPE_1_5'))
            it('Get MLA_CASE_SUB_TYPE_2_1', async() => serv.getMasterDataByCode('MLA_CASE_SUB_TYPE_2_1'))
            it('Get MLA_CASE_SUB_TYPE_2_2', async() => serv.getMasterDataByCode('MLA_CASE_SUB_TYPE_2_2'))
            it('Get MLA_CASE_SUB_TYPE_2_3', async() => serv.getMasterDataByCode('MLA_CASE_SUB_TYPE_2_3'))
            it('Get MLA_CASE_SUB_TYPE_2_4', async() => serv.getMasterDataByCode('MLA_CASE_SUB_TYPE_2_4'))
            it('Get MLA_CASE_SUB_TYPE_2_5', async() => serv.getMasterDataByCode('MLA_CASE_SUB_TYPE_2_5'))
            it('Get MLA_CASE_SUB_TYPE_3_1', async() => serv.getMasterDataByCode('MLA_CASE_SUB_TYPE_3_1'))
            it('Get MLA_CASE_SUB_TYPE_3_2', async() => serv.getMasterDataByCode('MLA_CASE_SUB_TYPE_3_2'))
            it('Get MLA_CASE_SUB_TYPE_3_3', async() => serv.getMasterDataByCode('MLA_CASE_SUB_TYPE_3_3'))
            it('Get MLA_CASE_SUB_TYPE_3_4', async() => serv.getMasterDataByCode('MLA_CASE_SUB_TYPE_3_4'))
            it('Get MLA_CASE_SUB_TYPE_3_5', async() => serv.getMasterDataByCode('MLA_CASE_SUB_TYPE_3_5'))
            it('Get MLA_CASE_SUB_TYPE_4_1', async() => serv.getMasterDataByCode('MLA_CASE_SUB_TYPE_4_1'))
            it('Get MLA_CASE_SUB_TYPE_4_2', async() => serv.getMasterDataByCode('MLA_CASE_SUB_TYPE_4_2'))
            it('Get MLA_CASE_SUB_TYPE_4_3', async() => serv.getMasterDataByCode('MLA_CASE_SUB_TYPE_4_3'))
            it('Get MLA_CASE_SUB_TYPE_4_4', async() => serv.getMasterDataByCode('MLA_CASE_SUB_TYPE_4_4'))
            it('Get MLA_CASE_SUB_TYPE_4_5', async() => serv.getMasterDataByCode('MLA_CASE_SUB_TYPE_4_5'))
            it('Get MLA_CASE_SUB_TYPE_5_1', async() => serv.getMasterDataByCode('MLA_CASE_SUB_TYPE_5_1'))
            it('Get MLA_CASE_SUB_TYPE_5_2', async() => serv.getMasterDataByCode('MLA_CASE_SUB_TYPE_5_2'))
            it('Get MLA_CASE_SUB_TYPE_5_3', async() => serv.getMasterDataByCode('MLA_CASE_SUB_TYPE_5_3'))
            it('Get MLA_CASE_SUB_TYPE_5_4', async() => serv.getMasterDataByCode('MLA_CASE_SUB_TYPE_5_4'))
            it('Get MLA_CASE_SUB_TYPE_5_5', async() => serv.getMasterDataByCode('MLA_CASE_SUB_TYPE_5_5'))
            it('Get MLA_CASE_TYPE_3', async() => serv.getMasterDataByCode('MLA_CASE_TYPE_3'))
            it('Get MLA_CASE_TYPE_4', async() => serv.getMasterDataByCode('MLA_CASE_TYPE_4'))
            it('Get MLA_CASE_TYPE_5', async() => serv.getMasterDataByCode('MLA_CASE_TYPE_5'))
            it('Get MLA-F', async() => serv.getMasterDataByCode('MLA-F'))
            it('Get MLA-T', async() => serv.getMasterDataByCode('MLA-T'))
            it('Get O', async() => serv.getMasterDataByCode('O'))
            it('Get REGISTRY (IAD)', async() => serv.getMasterDataByCode('REGISTRY (IAD)'))
            it('Get REQUEST_COMPLEXITY_1', async() => serv.getMasterDataByCode('REQUEST_COMPLEXITY_1'))
            it('Get REQUEST_COMPLEXITY_2', async() => serv.getMasterDataByCode('REQUEST_COMPLEXITY_2'))
            it('Get REQUEST_COMPLEXITY_3', async() => serv.getMasterDataByCode('REQUEST_COMPLEXITY_3'))
            it('Get REQUEST_COMPLEXITY_4', async() => serv.getMasterDataByCode('REQUEST_COMPLEXITY_4'))
            it('Get REQUEST_COMPLEXITY_5', async() => serv.getMasterDataByCode('REQUEST_COMPLEXITY_5'))
            it('Get REQUEST_MODE_1', async() => serv.getMasterDataByCode('REQUEST_MODE_1'))
            it('Get REQUEST_MODE_2', async() => serv.getMasterDataByCode('REQUEST_MODE_2'))
            it('Get REQUEST_MODE_3', async() => serv.getMasterDataByCode('REQUEST_MODE_3'))
            it('Get REQUEST_MODE_4', async() => serv.getMasterDataByCode('REQUEST_MODE_4'))
            it('Get REQUEST_MODE_5', async() => serv.getMasterDataByCode('REQUEST_MODE_5'))
            it('Get REQUESTED_UNDER_1', async() => serv.getMasterDataByCode('REQUESTED_UNDER_1'))
            it('Get REQUESTED_UNDER_2', async() => serv.getMasterDataByCode('REQUESTED_UNDER_2'))
            it('Get REQUESTED_UNDER_3', async() => serv.getMasterDataByCode('REQUESTED_UNDER_3'))
            it('Get REQUESTED_UNDER_4', async() => serv.getMasterDataByCode('REQUESTED_UNDER_4'))
            it('Get REQUESTED_UNDER_5', async() => serv.getMasterDataByCode('REQUESTED_UNDER_5'))
            it('Get REQUESTED_UNDER_6', async() => serv.getMasterDataByCode('REQUESTED_UNDER_6'))
            it('Get ROOT_CODE_1', async() => serv.getMasterDataByCode('ROOT_CODE_1'))
            it('Get RSTAT_A', async() => serv.getMasterDataByCode('RSTAT_A'))
            it('Get RSTAT_C', async() => serv.getMasterDataByCode('RSTAT_C'))
            it('Get RSTAT_D', async() => serv.getMasterDataByCode('RSTAT_D'))
            it('Get RSTAT_O', async() => serv.getMasterDataByCode('RSTAT_O'))
            it('Get RSTAT_R', async() => serv.getMasterDataByCode('RSTAT_R'))
            it('Get RSTAT_RJ', async() => serv.getMasterDataByCode('RSTAT_RJ'))
            it('Get RTYPE_ADV', async() => serv.getMasterDataByCode('RTYPE_ADV'))
            it('Get RTYPE_CCL', async() => serv.getMasterDataByCode('RTYPE_CCL'))
            it('Get RTYPE_MLA', async() => serv.getMasterDataByCode('RTYPE_MLA'))
            it('Get RURGENT_NU', async() => serv.getMasterDataByCode('RURGENT_NU'))
            it('Get RURGENT_U', async() => serv.getMasterDataByCode('RURGENT_U'))
            it('Get RURGENT_VU', async() => serv.getMasterDataByCode('RURGENT_VU'))
            it('Get SECURITY_CLASSIFICATION_1', async() => serv.getMasterDataByCode('SECURITY_CLASSIFICATION_1'))
            it('Get SECURITY_CLASSIFICATION_2', async() => serv.getMasterDataByCode('SECURITY_CLASSIFICATION_2'))
            it('Get SECURITY_CLASSIFICATION_3', async() => serv.getMasterDataByCode('SECURITY_CLASSIFICATION_3'))
            it('Get SECURITY_CLASSIFICATION_4', async() => serv.getMasterDataByCode('SECURITY_CLASSIFICATION_4'))
            it('Get SECURITY_CLASSIFICATION_5', async() => serv.getMasterDataByCode('SECURITY_CLASSIFICATION_5'))
        })
        describe('Fetch master data by types',() => {
            it('Get all master data by passing multiple types', async() => serv.getMasterDataByTypes('AGENCY_NAME_FOREIGN, AGENCY_TYPE_FOREIGN,'+ 
            'CASE_ACTIVITY_TYPE, CASE_COMPLEXITY, CASE_FATF, CASE_STATUS, COUNTRY, DEPARTMENT, DOCUMENT_TYPE, EXTERNAL_AGENCY_NAME, EXTERNAL_AGENCY_TYPE,'+ 
            'FILE_DIVISION, FILE_HEADER1, FILE_HEADER2, FILE_ORIGIN, FILE_YEAR, MLA_CASE_SUB_TYPE, MLA_CASE_TYPE, REQUEST_COMPLEXITY, REQUEST_MODE,'+ 
            'REQUEST_STATUS, REQUEST_TYPE, REQUEST_URGENCY, REQUESTED_UNDER, ROOT_CODE, SECURITY_CLASSIFICATION'))
        })
        describe('Fetch master data by codes',() => {
            it('Get all master data by passing multiple codes', async() => serv.getMasterDataByCodes('2019, 2020, 2021, 2022, 2023, ADDR_F, ADDR_L, ADVISORY,'+
            ' AGENCY_NAME_FOREIGN_1_1, AGENCY_NAME_FOREIGN_1_2, AGENCY_NAME_FOREIGN_1_3, AGENCY_NAME_FOREIGN_1_4, AGENCY_NAME_FOREIGN_1_5, '+
            'AGENCY_NAME_FOREIGN_2_1, AGENCY_NAME_FOREIGN_2_2, AGENCY_NAME_FOREIGN_2_3, AGENCY_NAME_FOREIGN_2_4, AGENCY_NAME_FOREIGN_2_5, AGENCY_NAME_FOREIGN_3_1, '+
            'AGENCY_NAME_FOREIGN_3_2, AGENCY_NAME_FOREIGN_3_3, AGENCY_NAME_FOREIGN_3_4, AGENCY_NAME_FOREIGN_3_5, AGENCY_NAME_FOREIGN_4_1, AGENCY_NAME_FOREIGN_4_2, '+
            'AGENCY_NAME_FOREIGN_4_3, AGENCY_NAME_FOREIGN_4_4, AGENCY_NAME_FOREIGN_4_5, AGENCY_NAME_FOREIGN_5_1, AGENCY_NAME_FOREIGN_5_2, AGENCY_NAME_FOREIGN_5_3, '+
            'AGENCY_NAME_FOREIGN_5_4, AGENCY_NAME_FOREIGN_5_5, AGENCY_TYPE_FOREIGN_1, AGENCY_TYPE_FOREIGN_2, AGENCY_TYPE_FOREIGN_3, AGENCY_TYPE_FOREIGN_4, '+
            'AGENCY_TYPE_FOREIGN_5, CASE_ACTIVITY_TYPE_1, CASE_ACTIVITY_TYPE_2, CASE_ACTIVITY_TYPE_3, CASE_ACTIVITY_TYPE_4, CASE_ACTIVITY_TYPE_5, CASE_COMPLEXITY_1, '+
            'CASE_COMPLEXITY_2, CASE_COMPLEXITY_3, CASE_COMPLEXITY_4, CASE_COMPLEXITY_5, CASE_FATF_1, CASE_FATF_2, CASE_FATF_3, CASE_FATF_4, CASE_FATF_5, CASE_STATUS_1, '+
            'CASE_STATUS_2, CASE_STATUS_3, CIRCULATION OFFICER, COUNTRY_1, COUNTRY_2, COUNTRY_3, COUNTRY_4, COUNTRY_5, CSTAT_DO, CSTAT_O, D1, D2, D3, '+
            'EXTERNAL_AGENCY_NAME_1_1, EXTERNAL_AGENCY_NAME_1_2, EXTERNAL_AGENCY_NAME_1_3, EXTERNAL_AGENCY_NAME_1_4, EXTERNAL_AGENCY_NAME_1_5, EXTERNAL_AGENCY_NAME_2_1, '+
            'EXTERNAL_AGENCY_NAME_2_2, EXTERNAL_AGENCY_NAME_2_3, EXTERNAL_AGENCY_NAME_2_4, EXTERNAL_AGENCY_NAME_2_5, EXTERNAL_AGENCY_NAME_3_1, EXTERNAL_AGENCY_NAME_3_2, '+
            'EXTERNAL_AGENCY_NAME_3_3, EXTERNAL_AGENCY_NAME_3_4, EXTERNAL_AGENCY_NAME_3_5, EXTERNAL_AGENCY_NAME_4_1, EXTERNAL_AGENCY_NAME_4_2, EXTERNAL_AGENCY_NAME_4_3, '+
            'EXTERNAL_AGENCY_NAME_4_4, EXTERNAL_AGENCY_NAME_4_5, EXTERNAL_AGENCY_NAME_5_1, EXTERNAL_AGENCY_NAME_5_2, EXTERNAL_AGENCY_NAME_5_3, EXTERNAL_AGENCY_NAME_5_4, '+
            'EXTERNAL_AGENCY_NAME_5_5, EXTERNAL_AGENCY_TYPE_1, EXTERNAL_AGENCY_TYPE_2, EXTERNAL_AGENCY_TYPE_3, EXTERNAL_AGENCY_TYPE_4, EXTERNAL_AGENCY_TYPE_5, EXTR-F, '+
            'EXTR-T, EXTRADITION, EXTRADITION_CASE, FILE_DIVISION_1_DOC_1, FILE_DIVISION_1_DOC_2, FILE_DIVISION_1_DOC_3, FILE_DIVISION_1_DOC_4, FILE_DIVISION_1_DOC_5, '+
            'FILE_DIVISION_2_DOC_1, FILE_DIVISION_2_DOC_2, FILE_DIVISION_2_DOC_3, FILE_DIVISION_2_DOC_4, FILE_DIVISION_2_DOC_5, FILE_DIVISION_3_DOC_1, FILE_DIVISION_3_DOC_2, '+
            'FILE_DIVISION_3_DOC_3, FILE_DIVISION_3_DOC_4, FILE_DIVISION_3_DOC_5, FILE_DIVISION_4, FILE_DIVISION_4_DOC_1, FILE_DIVISION_4_DOC_2, FILE_DIVISION_4_DOC_3, '+
            'FILE_DIVISION_4_DOC_4, FILE_DIVISION_4_DOC_5, FILE_DIVISION_5, FILE_DIVISION_5_DOC_1, FILE_DIVISION_5_DOC_2, FILE_DIVISION_5_DOC_3, FILE_DIVISION_5_DOC_4, '+
            'FILE_DIVISION_5_DOC_5, FILE_HEADER1_1_2, FILE_HEADER1_1_3, FILE_HEADER1_1_4, FILE_HEADER1_1_5, FILE_HEADER1_2_2, FILE_HEADER1_2_3, FILE_HEADER1_2_4, '+
            'FILE_HEADER1_2_5, FILE_HEADER1_3_2, FILE_HEADER1_3_3, FILE_HEADER1_3_4, FILE_HEADER1_3_5, FILE_HEADER1_4_1, FILE_HEADER1_4_2, FILE_HEADER1_4_3, FILE_HEADER1_4_4, '+
            'FILE_HEADER1_4_5, FILE_HEADER1_5_1, FILE_HEADER1_5_2, FILE_HEADER1_5_3, FILE_HEADER1_5_4, FILE_HEADER1_5_5, FILE_HEADER2_1_2, FILE_HEADER2_1_3, FILE_HEADER2_1_4, '+
            'FILE_HEADER2_2_3, FILE_HEADER2_2_4, FILE_HEADER2_2_5, FILE_HEADER2_3_1, FILE_HEADER2_3_2, FILE_HEADER2_3_3, FILE_HEADER2_3_4, FILE_HEADER2_3_5, FILE_HEADER2_4_1, '+
            'FILE_HEADER2_4_2, FILE_HEADER2_4_3, FILE_HEADER2_4_4, FILE_HEADER2_4_5, FILE_HEADER2_5_1, FILE_HEADER2_5_2, FILE_HEADER2_5_3, FILE_HEADER2_5_4, FILE_HEADER2_5_5, '+
            'I, LEGAL OFFICER, MLA, MLA_CASE, MLA_CASE_SUB_TYPE_1_3, MLA_CASE_SUB_TYPE_1_4, MLA_CASE_SUB_TYPE_1_5, MLA_CASE_SUB_TYPE_2_1, MLA_CASE_SUB_TYPE_2_2, '+
            'MLA_CASE_SUB_TYPE_2_3, MLA_CASE_SUB_TYPE_2_4, MLA_CASE_SUB_TYPE_2_5, MLA_CASE_SUB_TYPE_3_1, MLA_CASE_SUB_TYPE_3_2, MLA_CASE_SUB_TYPE_3_3, MLA_CASE_SUB_TYPE_3_4, '+
            'MLA_CASE_SUB_TYPE_3_5, MLA_CASE_SUB_TYPE_4_1, MLA_CASE_SUB_TYPE_4_2, MLA_CASE_SUB_TYPE_4_3, MLA_CASE_SUB_TYPE_4_4, MLA_CASE_SUB_TYPE_4_5, MLA_CASE_SUB_TYPE_5_1, '+
            'MLA_CASE_SUB_TYPE_5_2, MLA_CASE_SUB_TYPE_5_3, MLA_CASE_SUB_TYPE_5_4, MLA_CASE_SUB_TYPE_5_5, MLA_CASE_TYPE_3, MLA_CASE_TYPE_4, MLA_CASE_TYPE_5, MLA-F, MLA-T, O, '+
            'REGISTRY (IAD), REQUEST_COMPLEXITY_1, REQUEST_COMPLEXITY_2, REQUEST_COMPLEXITY_3, REQUEST_COMPLEXITY_4, REQUEST_COMPLEXITY_5, REQUEST_MODE_1, REQUEST_MODE_2, '+
            'REQUEST_MODE_3, REQUEST_MODE_4, REQUEST_MODE_5, REQUESTED_UNDER_1, REQUESTED_UNDER_2, REQUESTED_UNDER_3, REQUESTED_UNDER_4, REQUESTED_UNDER_5, '+
            'REQUESTED_UNDER_6, ROOT_CODE_1, RSTAT_A, RSTAT_C, RSTAT_D, RSTAT_O, RSTAT_R, RSTAT_RJ, RTYPE_ADV, RTYPE_CCL, RTYPE_MLA, RURGENT_NU, RURGENT_U, RURGENT_VU, '+
            'SECURITY_CLASSIFICATION_1, SECURITY_CLASSIFICATION_2, SECURITY_CLASSIFICATION_3, SECURITY_CLASSIFICATION_4, SECURITY_CLASSIFICATION_5'))
        })
    })
    after(() => {
        console.log(`Total test cases - ${totalCases}`)
    })
})